INPUT_NEURONS = 4
OUT_NEURONS = 1
H_NEURONS = 25
LEARNING_RATE = 0.003
EPOCHS = 20000
TRAIN_DATA_SHARE = 0.7
TEST_DATA_SHARE = 0.3
EPS = 0.01

FILE_NAME_INPUT_DATA = "task_dataset100.csv"
FILE_NAME_WEIGHTS = "weights_size.txt"
FILE_NAME_BIAS = "bias_size.txt"
