INPUT_NEURONS = 4
OUT_NEURONS = 1
H_NEURONS = 3
LEARNING_RATE = 0.01
EPOCHS = 1000
TRAIN_DATA_SHARE = 0.7
TEST_DATA_SHARE = 0.3
EPS = 0.1

FILE_NAME_INPUT_DATA = "task_dataset100.csv"
FILE_NAME_WEIGHTS = "weights_size.txt"
FILE_NAME_BIAS = "bias_size.txt"